import axios from "axios";
import Head from "next/head";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Results from "../components/Results";
import FETCH from "../utils/req";

export default function Home({ results, type }) {
  return (
    <div>
      <Head>
        <title>NEXTHulu by Ara Gamaliel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <Results results={results} type={type} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  try {
    const res = await axios.get(
      `https://api.themoviedb.org/3${
        FETCH[genre]?.url || FETCH.trending.url
      }&sort_by=popularity.desc`
    );
    const data = res.data.results;
    return {
      props: {
        results: data,
        type: FETCH[genre]?.type || null,
      },
    };
  } catch (err) {
    console.log(err);
  }
}
